# REST Client

@baseUrl = http://localhost:63836
#@baseUrl = http://139.155.8.217

@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NjgzNzg2NTEsImV4cCI6MTU3NzAxODY1MSwiaXNzIjoiaHR0cDovLzEzOS4xNTUuOC4yMTciLCJhdWQiOlsiaHR0cDovLzEzOS4xNTUuOC4yMTcvcmVzb3VyY2VzIiwiQXBwQXBpIl0sImNsaWVudF9pZCI6IkFwcC5NYW5hZ2VyLlJvIiwic3ViIjoiNSIsImF1dGhfdGltZSI6MTU2ODM3ODY1MSwiaWRwIjoiIiwicm9sZSI6IjEiLCJzY29wZSI6WyJBcHBBcGkiXSwiYW1yIjpbImN1c3RvbSJdfQ.DrGWlWSIbl9M4nQMs0m-XMmwUm2MC7FQF8NiItfYMIrusLrTrx15s5RmI8938l_Pfa_CrUocUE1KL7qGfZJkniCZdsX_ENbvj83NctwITXYFijIlg0zO1wfdVGgPIRZ8aeIAAhn6dVnc5EZ1yIeEhFhjRyEM8KWmZqAZYNTPq7ThW_sOUesZCxAsFfdv_fMc4h2jIUm_RsjxLcHv1iv1Yp-ThJZprfU2FCzqEsR0Gkn5I-F7lNS8tJGjODwHBJVlosyXmvFpfQBa6ltqNhK5D7lNuq_fuQfckTAK24oLkjhIPXjWfcFbfaUawn3jemrPrcAFkIEZQTqv0hL0hz9urA
@contentType = application/json

# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=admin&password=123456

###############################################登录注册###############################################
### 注册
POST {{baseUrl}}/api/Member/PostRegisterUser HTTP/1.1
Content-Type: {{contentType}}

{
    "phone": "18624938013",
    "password": "123456",
    "mail": "yymcct@qq.com",
    "invitePhone":"18624938007"
}
### 获取推荐人电话
GET {{baseUrl}}/api/Member/GetInviteUserPhone?id=1

### 获取我的团队信息
GET {{baseUrl}}/api/Member/GetMyTeam
Authorization: Bearer {{token}}

### 获取我的团队未绑卡的用户
GET {{baseUrl}}/api/Member/GetMyTeamNoCardUser
Authorization: Bearer {{token}}

### 修改密码
###############################################获取卡片信息###############################################
GET {{baseUrl}}/api/BankCard/Gets
        ?sorts=id,
        &Page=1
        &PageSize=10
Authorization: Bearer {{token}}

### 获取银行卡详情信息
GET {{baseUrl}}/api/BankCard/GetCardContent?id=3
Authorization: Bearer {{token}}

### 提交卡片信息
POST {{baseUrl}}/api/BankCard/Post
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "Id": "0",
    "CardNum": "6888888881",
    "Bank": "0",
    "Email": "yymcct@qq.com",
    "Password": "123456123456123456",
    "Remark": "没有什么好备注的",
}
### 修改卡片信息
POST {{baseUrl}}/api/BankCard/Post
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "Id": "1",
    "CardNum": "201909060002",
    "Bank": "0",
    "Email": "yymcct@qq.com",
    "Password": "123456",
    "Remark": "没有什么好备注的",
}

### 删除卡片信息
GET {{baseUrl}}/api/BankCard/Delete?id=1
Authorization: Bearer {{token}}


### 获取个人银行卡汇总信息
GET {{baseUrl}}/api/BankCard/GetCardTotal
Authorization: Bearer {{token}}

### 测试邮箱
GET {{baseUrl}}/api/Values/GetQQmailAsync









