# REST Client

@baseUrl = http://localhost:63836
#@baseUrl = http://192.168.0.214:5000
#@baseUrl = http://122.114.157.240:5000
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1Njc3NTM5MjgsImV4cCI6MTU2Nzc4MjcyOCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MzgzNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYzODM2L3Jlc291cmNlcyIsIkFwcEFwaSJdLCJjbGllbnRfaWQiOiJBcHAuTWFuYWdlci5SbyIsInN1YiI6IjUiLCJhdXRoX3RpbWUiOjE1Njc3NTM5MjcsImlkcCI6IiIsInJvbGUiOiIxIiwic2NvcGUiOlsiQXBwQXBpIl0sImFtciI6WyJjdXN0b20iXX0.bfnHpihveYBJ9T60oDzKplKVLSvn2i52uQfZH5xmjBqqocGVgGVCBwNyZao6a2bFERmwC5pbnesao7SrFSJ-u1QaWPgMEedTDMUuY9XDxsqs1ztcLRNokYi1N4FGcOF779kQ8cKe6mitVhYJ9z4odRLfagPAgPzZbVPLV4lCsgDfkRbU9nc4A6zYgcziGCUjzbDueeIw_X2I-UpV7ogxqLVAf0Rla7as4BKQpgfu7Xb4pzcI07yHqpoymqZZLRsUMfWFHXvxInB6KgR7xl5AVOBzTn4H5R93Ct2eqV1t40HYAapOey8N2g8PXCZdauyuaMZJ994wQLruCOeeT6eAjw
@contentType = application/json

# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=admin&password=123456

###############################################登录注册###############################################
### 注册
POST {{baseUrl}}/api/Member/PostRegisterUser HTTP/1.1
Content-Type: {{contentType}}

{
    "phone": "18624938009",
    "password": "123456",
    "mail": "yymcct@qq.com",
}

### 修改密码
###############################################获取卡片信息###############################################
GET {{baseUrl}}/api/BankCard/BankCard
        ?Filters=,
        &sorts=,
        &Page=1
        &PageSize=10
Authorization: Bearer {{token}}

### 提交卡片信息
POST {{baseUrl}}/api/BankCard/Post
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "Id": "0",
    "CardNum": "201909060001",
    "Bank": "0",
    "Email": "yymcct@qq.com",
    "Password": "123456",
    "Remark": "没有什么好备注的",
}
### 修改卡片信息
POST {{baseUrl}}/api/BankCard/Post
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "Id": "1",
    "CardNum": "201909060002",
    "Bank": "0",
    "Email": "yymcct@qq.com",
    "Password": "123456",
    "Remark": "没有什么好备注的",
}


### 获取已审核信息
GET {{baseUrl}}/manager/AutoSendMessage/GetAutoSendMessages
        ?Filters=,
        &sorts=,
        &Page=1
        &PageSize=10
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/Categories/PostCategory HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "ParentId": 0,
    "Iteam": 1,
    "Column": 1,
    "Name":"测试3",
    "PicUrl":"www.baidu.com",
    "Url":"baidu",
    "Order": 12,
    "RemoteCategoryId":122,
    "RemoteCategoryName":"测试",
    "OpUser":"翁奎"
}
###
GET  {{baseUrl}}/manager/1000/Categories/DeleteCategory?id=1023 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


############################################### Member ###############################################
### 获取用户信息
GET {{baseUrl}}/manager/1000/Member/GetUser HTTP/1.1
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/manager/1000/Member/GetUsers
    ?filters=Phone==18624938007,RealName==翁奎
    &sorts=-OpTime
    &Page=1
    &PageSize=10
Authorization: Bearer {{token}}

### 注册
Post {{baseUrl}}/manager/1000/Member/PostUser
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "RoleId":0,
    "Phone": 18864275120,
    "Password": 123,
    "TopRegionId":0,
    "RegionId":0
}



###
POST {{baseUrl}}/manager/1000/ShortMsgFavorite/PostShortMsgFavorite HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "CategoryIteam": 3,
    "ShortMsgId": 9,
    "memberId": 9
}
###
Get {{baseUrl}}/manager/1000/ShortMsgFavorite/DeleteShortMsgFavorite?id=3 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################动态列表#########################################################

GET {{baseUrl}}/manager/1000/ShortMsg/GetShortMsgs
        ?Filters=addTime<=2019-07-03
        &Page=1
        &PageSize=10
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortMsg/PostShortMsg HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 3,
    "CategoryId": 247,
    "Content":"今天天气不错啊，有没有去农药市场去看看的呢？组团啦",
    "Address":"河南省国家大学科技园旁边的小山村",
}
###
Get {{baseUrl}}/manager/1000/ShortMsg/DeleteShortMsg?id=7066 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################动态评论列表#########################################################

GET {{baseUrl}}/manager/1000/ShortMsgReply/GetShortMsgReplys
        ?Filters=content@=东西
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortMsgReply/PostShortMsgReply HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 3,
    "Content":"看那东西南北风，吹着不同的脸庞",
    "shortMsgId":1,
}
###
Get {{baseUrl}}/manager/1000/ShortMsgReply/DeleteShortMsgReply?id=6111 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################动态评论列表#########################################################

GET {{baseUrl}}/manager/1000/CompanyFavorite/GetCompanyFavorites
        ?Filters=categoryIteam==3
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/CompanyFavorite/PostCompanyFavorite HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 3,
    "companyId":"521",
}
###
Get {{baseUrl}}/manager/1000/CompanyFavorite/DeleteCompanyFavorite?id=5005
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


############################################新闻收藏列表#########################################################

GET {{baseUrl}}/manager/1000/NewsFavorite/GetNewsFavorites
        ?Filters=categoryIteam==3,remoteCategoryName==行业动态
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/NewsFavorite/PostNewsFavorite HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 3,
    "newsId":"1126453",
    "remoteCategoryId":"IndustryNew",
    "remoteCategoryName":"行业动态"
}
###
Get {{baseUrl}}/manager/1000/NewsFavorite/DeleteNewsFavorite?id=3004
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
###

GET {{baseUrl}}/api/Default/ HTTP/1.1
Authorization: Bearer {{token}}



############################################产品收藏列表#########################################################

GET {{baseUrl}}/manager/1000/ProductFavorite/GetProductFavorites
        ?Filters=categoryIteam==6
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ProductFavorite/PostProductFavorite HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 6,
    "productId":"11315"
}
###
Get {{baseUrl}}/manager/1000/ProductFavorite/DeleteProductFavorite?id=6010
Content-Type: {{contentType}}
Authorization: Bearer {{token}}





############################################新闻评论列表#########################################################

GET {{baseUrl}}/manager/1000/NewsReply/GetNewsReplys
        ?Filters=content@=看见爱上肯定就爱上看见爱上科技大会上
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/NewsReply/PostNewsReply HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 9,
    "CategoryIteam": 3,
    "newsId":"14785",
    "newsRemoteCategoryId":"CompanyNew",
    "newsRemoteCategoryName":"公司新闻",
    "content":"阿萨德哈哈大师的看见爱上肯定就爱上看见爱上科技大会上"
}
###
Get {{baseUrl}}/manager/1000/NewsReply/DeleteNewsReply?id=74
Content-Type: {{contentType}}
Authorization: Bearer {{token}}




############################################动态分享记录列表#########################################################

GET {{baseUrl}}/manager/1000/ShortMsgShare/GetShortMsgShares
        ?Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortMsgShare/PostShortMsgShare HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "MemberId": 10,
    "ShortMsgId": 6111,
    "SourceShortMemberId":"9"
}
###
Get {{baseUrl}}/manager/1000/ShortMsgShare/DeleteShortMsgShare?id=1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}




############################################动态点赞记录列表#########################################################

GET {{baseUrl}}/manager/1000/ShortMsgThumbsUp/GetShortMsgThumbsUps
        ?Filters=memberid==9,addTime>=2019-08-03 14:47:16,addTime<=2019-08-04 14:47:16
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortMsgThumbsUp/PostShortMsgThumbsUp HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "Id":3052,
    "MemberId": 9,
    "state":1
}
###
Get {{baseUrl}}/manager/1000/ShortMsgThumbsUp/DeleteShortMsgThumbsUp?id=3052
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


############################################短视频列表#########################################################

GET {{baseUrl}}/manager/1000/ShortVideo/GetShortVideos
        ?Filters=memberid==9,address@=科技园
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortVideo/PostShortVideo HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "categoryIteamId":3,
    "MemberId": 9,
    "videoUrl":"http://1258661673.vod2.myqcloud.com/22a959cfvodcq1258661673/23e79dcf5285890792001653587/7nqhf9sic4AA.mp4",
    "address":"科技园2楼"
}
###
Get {{baseUrl}}/manager/1000/ShortVideo/DeleteShortVideo?id=5017
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################短视频收藏记录列表#########################################################

GET {{baseUrl}}/manager/1000/ShortVideoFavorite/GetShortVideoFavorites
        ?Filters=memberId==10
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortVideoFavorite/PostShortVideoFavorite HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "categoryIteamId":3,
    "MemberId": 10,
    "shortVideoId":"5"
}
###
Get {{baseUrl}}/manager/1000/ShortVideoFavorite/DeleteShortVideoFavorite?id=2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################短视频评论列表#########################################################

GET {{baseUrl}}/manager/1000/ShortVideoReply/GetShortVideoReplys
        ?Filters=content@=不错
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortVideoReply/PostShortVideoReply HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "categoryIteamId":3,
    "shortVideoId":5,
    "MemberId": 10,
    "content":"肯定不错啊"
}
###
Get {{baseUrl}}/manager/1000/ShortVideoReply/DeleteShortVideoReply?id=1002
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################短视频点赞记录表#########################################################

GET {{baseUrl}}/manager/1000/ShortVideoThumbsUp/GetShortVideoThumbsUps
        ?Filters=memberId==9
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortVideoThumbsUp/PostShortVideoThumbsUp HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "memberId":3,
    "shortVideoId":5017
}
###
Get {{baseUrl}}/manager/1000/ShortVideoThumbsUp/DeleteShortVideoThumbsUp?id=2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}



############################################用户关注记录表#########################################################

GET {{baseUrl}}/manager/1000/MemberFollow/GetMemberFollows
        ?Filters=memberId==10
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/MemberFollow/PostMemberFollow HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "memberId":9,
    "followedMemberId":2
}
###
Get {{baseUrl}}/manager/1000/MemberFollow/DeleteMemberFollow?id=7064
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

############################################用户登录记录表#########################################################

GET {{baseUrl}}/manager/1000/UserLoginLog/GetUserLoginLogs
        ?Filters=phone==18864275125
        &Page=1
        &PageSize=10
        &sorts=-opTime
Authorization: Bearer {{token}}

############################################管理员操作记录表#########################################################

GET {{baseUrl}}/manager/1000/AdminWorkLog/GetAdminWorkLogs
        ?Filters=opUserName1222==15138660814
        &Page=1
        &PageSize=10
        &sorts=-opTime
Authorization: Bearer {{token}}

############################################用户操作记录表#########################################################

GET {{baseUrl}}/manager/1000/UserWorkLog/GetUserWorkLogs
        ?Filters=opUserName@=南边
        &Page=1
        &PageSize=10
        &sorts=-opTime
Authorization: Bearer {{token}}


############################################系统配置表#########################################################

GET {{baseUrl}}/manager/1000/SystemConfig/GetSystemConfigs
        ?Filters=configsType==1
        &Page=1
        &PageSize=10
        &sorts=-opTime
Authorization: Bearer {{token}}



############################################代理意向#########################################################

GET {{baseUrl}}/manager/1000/DLMessage/GetDLMessage
        ?Filters=configsType==1
        &Page=1
        &PageSize=10
Authorization: Bearer {{token}}



############################################敏感词汇表#########################################################

GET {{baseUrl}}/manager/1000/BadWord/GetBadWords
        ?Filters=opuserid==9
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/BadWord/PostBadWord HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "value":""
}
###
Get {{baseUrl}}/manager/1000/BadWord/DeleteBadWord?id=24
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


############################################短视频背景音乐标签表#########################################################

GET {{baseUrl}}/manager/1000/ShortVideoBgmTags/GetShortVideoBgmTagss
        ?Filters=opuserid==9
        &Page=1
        &PageSize=10
        &sorts=-addTime
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/manager/1000/ShortVideoBgmTags/PostShortVideoBgmTags HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "name":"叮2咚"
}
###
Get {{baseUrl}}/manager/1000/ShortVideoBgmTags/DeleteShortVideoBgmTags?id=24
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


###
Get http://localhost:65136/api/Posts/GetAll?Filters=id==1

###
Get http://localhost:65136/api/Posts/Create

###
Get http://localhost:65136/api/Posts/GetAllWithSieve
        ?Filters=id==1