# REST Client
@baseUrl = http://localhost:63836
#@baseUrl = http://localhost:52878
#@baseUrl = http://192.168.0.214:5000
#@baseUrl = http://122.114.157.240:8822
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE2MTIzMTYxNTgsImV4cCI6MTYyMDk1NjE1OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MzgzNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYzODM2L3Jlc291cmNlcyIsIkFwcEFwaSJdLCJjbGllbnRfaWQiOiJBcHAuTWFuYWdlci5SbyIsInN1YiI6IjcyIiwiYXV0aF90aW1lIjoxNjEyMzE2MTU4LCJpZHAiOiIiLCJyb2xlIjoiQWRtaW4iLCJzY29wZSI6WyJBcHBBcGkiXSwiYW1yIjpbImN1c3RvbSJdfQ.GzMGRv4zKIdNqfMR7Vp3VCDiloVT1CaidFxGaw6R6_dvZdIlu9Xwzc0-hsiYlS7BgNiIT0m3UjGkxtZqf5YvriOYN36XrnYvKzRpIVHlH8I_OlJVPQhB7XkDpGf9z4Rpgc8FXsQoheFtdqjnZBpHdr9zOU08bMmOn4LBiGKHIm9WDd_YR_vz2NcPeLey-bfUcq3aJploE5aKpY2NaNzEwaRF41wT_FlIsT5hCD0ZEDKZFSXhWa4Y2kSZaC_QSG55B8P30aH4P1UAI7Azs5NAfefov_Ca9bVThlgvJyctL477qPZ_xTEEnjjhtJpm0rJgC7zEWR7YqvSBFlXzeNunEg
@contentType = application/json


# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=18624938007&password=123456

### 登录
POST {{baseUrl}}/api/Member/H5
Content-Type: {{contentType}}

{
    "Account":"18624938007",
    "Password":"68771803"
}
###


###############################################AutoSendMessages###############################################
### 获取已审核信息
GET {{baseUrl}}/api/Values/Get
#Authorization: Bearer {{token}}
###
###
GET {{baseUrl}}/api/Alipay/GetH5UpdateVip1Order?toVipType=2
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/Alipay/WapPay/1773
Authorization: Bearer {{token}}


### Order
GET {{baseUrl}}/api/Order/1762
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/Order
Authorization: Bearer {{token}}

###
Post {{baseUrl}}/api/Order/12
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/Alipay/WapNotifyurl
Content-Type: application/x-www-form-urlencoded

charset=UTF-8&seller_email=19202490@qq.com&subject=补差价拍此处&sign=I41td3Rbvlt21ka6pZNJortIqzO/36Nz4QLZtu25+nGTZ+7UB7uT9TtXXvdhpZv3TdD1ELoUHuiLEakAeoGsk61jz0vQlgr4NlAr+XqBXldPKVrueOcNS87L27/+zqZ9f/QGsispHQdFrvPNDQukvvV9CaWKqFPtBc8GVqgO+MVpVJxuLqN2w6sro4m24FqnwiuQD0Z69bDI1rW4kOoueBb2vkAtMXkzPfbOdLprTAxIC3mfFkr4tYCDbiGyGnSmFbDGsYIKnVYuM6gR6EUv+EIyN+rpKbSVbfjgx3zois0VG9pLZVRCipX54ZQiGYDl9Gd1Re2NzsFy4wbZ3E6iVw==&body=补差价拍此处&buyer_id=2088102054494074&invoice_amount=0.10&notify_id=2020101000222223454094071439424061&fund_bill_list=[{"amount"="0.10","fundChannel"="ALIPAYACCOUNT"}]&notify_type=trade_status_sync&trade_status=TRADE_SUCCESS&receipt_amount=0.10&buyer_pay_amount=0.10&app_id=2017121200619628&sign_type=RSA2&seller_id=2088921018323595&gmt_payment=2020-10-10 22=34=53&notify_time=2020-10-10 22=34=54&version=1.0&out_trade_no=20201010223429193119&total_amount=0.10&trade_no=2020101022001494071401731570&auth_app_id=2017121200619628&buyer_logon_id=yym***@163.com&point_amount=0.00

###
POST {{baseUrl}}/api/Biqilin/Notifyurl
Content-Type: {{contentType}}

{
  "outOrderNo":"20210106093229312077",
  "orderStatus":"TRADE_SUCCESS"
}

###

POST http://139.155.8.217/api/Biqilin/Notifyurl
Content-Type: {{contentType}}

{
  "outOrderNo":"20210106095303476660",
  "orderStatus":"TRADE_SUCCESS"
}

### 获取二维码
Post {{baseUrl}}/api/Alipay/ScanCodeGen/1783
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


#### 测试支付
Post {{baseUrl}}/api/Biqilin/CreateQrcodePayUrl?orderId=1783
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 测试中信支付
Post {{baseUrl}}/api/Citicbank/ScanCodeGen?orderId=4320
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### 测试中信支付
Post {{baseUrl}}/manager/WechatSubLedger/ProfitsharingFinish
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "transaction_id":"4200000930202102067722259418",
  "last_out_order_no":"SH20210206171133444101",
  "description":"分账结束"
}


### 测试中信支付JsApi
Post {{baseUrl}}/api/Citicbank/JsApi?orderId=4320
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

###
POST {{baseUrl}}/api/Citicbank/Notifyurl HTTP/1.1
Content-Type: {{contentType}}

{
  "outOrderNo":"20210106095303476660",
  "orderStatus":"TRADE_SUCCESS"
}


### 测试服务接口
GET {{baseUrl}}/fuwu/product?sorts=-id&page=1&pagesize=10
###
GET {{baseUrl}}/fuwu/order?sorts=-id&page=1&pagesize=10












### 获取token # merchant_account=1100000522&merchant_pwd=123456&partner_code=taiyangniao&key=eb7KG4mZIhFmDnGG
Post  https://pay.biqilin.com/api/user/partner/key_download.do
Content-Type: application/x-www-form-urlencoded

merchant_account=1100000522&merchant_pwd=123456&partner_code=taiyangniao&sign=FE30C00A7823EEE67F7E57474BC7B9B2
### 应答的信息
{
  "detail": {
    "merchantName": "河南多宝格信息科技有限公司",
    "serviceMerchantName": "太阳鸟",
    "serviceMerchantAccount": "8100000004",
    "merchantAccount": "1100000522",
    "serviceMerchantPhone": "13598403073",
    "sign": "B59045C664C1197590C081AE876E6CE4",
    "token": "326b5d06397c08c379b447f1917d6ce38db006d43c31da324b4358eda54911f8"
  },
  "errorCode": "",
  "errorMsg": "",
  "flag": 1
}
### amount=0.10&fee_type=CNY&local_time=1603361351508&merchant_account=1100000522&notify_url=http://www.baidu.com&out_cashier_name=测试1&out_goods_name=测试商品&out_store_name=admin&out_trade_no=20200223&partner_code=taiyangniao&pay_type=WEIXIN_PAY&terminal_type=3&token=326b5d06397c08c379b447f1917d6ce38db006d43c31da324b4358eda54911f8&
POST https://pay.biqilin.com/api/pay/partner/qrcode_pay2.do
Content-Type: application/x-www-form-urlencoded

amount=0.10&fee_type=CNY&local_time=1610788393919&merchant_account=1100000522&notify_url=http://www.baidu.com&out_cashier_name=APP&out_goods_name=测试商品&out_store_name=admin&out_trade_no=20200222&partner_code=taiyangniao&pay_type=WEIXIN_PAY&terminal_type=3&token=326b5d06397c08c379b447f1917d6ce38db006d43c31da324b4358eda54911f8&sign=3EF528627B1AF98ED09269448D1F5FB4



### 

GET {{baseUrl}}/api/Report
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/manager/WechatSubLedger/SyncXtsuoOrders?startTime='2021-02-14'&endTime='2021-02-15'
Authorization: Bearer {{token}}