# REST Client
@baseUrl = http://localhost:63836
#@baseUrl = http://localhost:52878
#@baseUrl = http://192.168.0.214:5000
#@baseUrl = http://122.114.157.240:8822
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE2MDE0NzAzMjYsImV4cCI6MTYxMDExMDMyNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MzgzNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYzODM2L3Jlc291cmNlcyIsIkFwcEFwaSJdLCJjbGllbnRfaWQiOiJBcHAuTWFuYWdlci5SbyIsInN1YiI6IjcyIiwiYXV0aF90aW1lIjoxNjAxNDcwMzI2LCJpZHAiOiIiLCJyb2xlIjoiQWRtaW4iLCJzY29wZSI6WyJBcHBBcGkiXSwiYW1yIjpbImN1c3RvbSJdfQ.AVgzc0XIiw3X-E6zuNGy4aaS2PbUllVkWr5D01pEQZ1_a3CgEZcZUtXz_BT9X8emco40KfghMO58y135q3RTy8q2HJAExNMN9vPLlyXHe5O06_-LeXVXPHjZjBRKrKERok8EIT3pcMsnAzzTbVbkj7TLVsJ_qbH01XK66qXGPT89M1NyvW2bn2gooRgGV4rfuXQVSevz17lxpwJARE9D9nRO7iUDFIv4jTvt2yEc-5gVHxAqx3-X8Sc7wP6zTc3rCZEpTXYLLntqlLa-H6DiXRsMVQYYJJOMvELURJUj_SdxQMbSOBCw886h7-HMPjl3jog1aCxR4gbAW8Kgv6P4kg
@contentType = application/json


# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=wengkui&password=wengkui3456

###############################################AutoSendMessages###############################################
### 获取已审核信息
GET {{baseUrl}}/api/Values/Get
#Authorization: Bearer {{token}}
###
###
GET {{baseUrl}}/api/Alipay/GetH5UpdateVip1Order?toVipType=2
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/Alipay/WapPay/1773
Authorization: Bearer {{token}}


### Order
GET {{baseUrl}}/api/Order/1762
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/Order
Authorization: Bearer {{token}}

###
Post {{baseUrl}}/api/Order/12
Authorization: Bearer {{token}}