// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xw.Zx.Core.Models.Model;

namespace Xw.Zx.Core.Migrations
{
    [DbContext(typeof(XwZxContext))]
    [Migration("20190906105218_editbank1")]
    partial class editbank1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bank");

                    b.Property<string>("CardNum");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<int>("MemberId");

                    b.Property<string>("Password");

                    b.Property<string>("Remark");

                    b.HasKey("Id");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MailSrc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Body");

                    b.Property<string>("BodyEncoding");

                    b.Property<string>("From");

                    b.Property<DateTime>("SendTime");

                    b.Property<string>("Sublic");

                    b.Property<string>("To");

                    b.Property<string>("Uid");

                    b.HasKey("Id");

                    b.ToTable("MailSrcs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("BirthDay");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastLoginDate");

                    b.Property<string>("Nick");

                    b.Property<string>("Occupation");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordSalt");

                    b.Property<string>("Phone");

                    b.Property<string>("Photo");

                    b.Property<string>("QQ");

                    b.Property<string>("RealName");

                    b.Property<int>("RegionId");

                    b.Property<string>("Remark");

                    b.Property<int>("RoleId");

                    b.Property<string>("RoleName");

                    b.Property<int>("Sex");

                    b.Property<int>("TopRegionId");

                    b.Property<string>("UserName");

                    b.Property<string>("WxOpenId");

                    b.Property<string>("WxUnionId");

                    b.Property<string>("WxUnionOpenId");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
