// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xw.Zx.Core.Models.Model;

namespace Xw.Zx.Core.Migrations
{
    [DbContext(typeof(XwZxContext))]
    [Migration("20210119135151_editwebSubDetail")]
    partial class editwebSubDetail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.AlipayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("PaymentId");

                    b.Property<string>("code");

                    b.Property<string>("msg");

                    b.Property<string>("order_id");

                    b.Property<string>("out_biz_no");

                    b.Property<string>("pay_date");

                    b.Property<string>("sub_code");

                    b.Property<string>("sub_msg");

                    b.HasKey("Id");

                    b.ToTable("AlipayLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<int>("AppPlatform");

                    b.Property<string>("DownLoadUrl");

                    b.Property<bool>("IsAllUpdate");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Version");

                    b.Property<string>("WithPhones");

                    b.HasKey("Id");

                    b.ToTable("AppVersions");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.ApplyForZxMDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<int>("ApplyForZxState");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<string>("Remark");

                    b.HasKey("Id");

                    b.ToTable("ApplyForZxs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.BankBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankCardId");

                    b.Property<DateTime>("CycleStart");

                    b.Property<DateTime>("CycleStop");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<decimal>("Limit");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("OverdueFine");

                    b.Property<DateTime>("PaymentDueData");

                    b.HasKey("Id");

                    b.ToTable("BankBills");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.BankBillDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("Bank");

                    b.Property<string>("CardNum");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MailId");

                    b.Property<int>("MemberID");

                    b.Property<string>("SellerName");

                    b.Property<DateTime?>("TreadTime");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("BankBillDetails");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bank");

                    b.Property<string>("CardNum");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("LastSyncIsOk");

                    b.Property<DateTime?>("LastSyncTime");

                    b.Property<int>("MemberId");

                    b.Property<decimal>("OverdueFine")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Password");

                    b.Property<string>("Remark");

                    b.HasKey("Id");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.BiqilinLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BiqilinOrderNo");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.ToTable("BiqilinLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CurCount");

                    b.Property<DateTime>("EndTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("TotalCount");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.CouponReceive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CouponUseState");

                    b.Property<int>("Couponid");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Memberid");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Couponid");

                    b.ToTable("CouponReceives");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.CouponUseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CouponReceiveid");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Orderid");

                    b.Property<int>("Productid");

                    b.HasKey("Id");

                    b.ToTable("CouponUseLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.IncomeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("AuditMemberId");

                    b.Property<DateTime>("Auditime");

                    b.Property<int>("IncomeAccountState");

                    b.Property<int>("IncomeAccountType");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<string>("Remark");

                    b.Property<int>("SourceOrderId");

                    b.Property<int>("SourceOrderMemberId");

                    b.Property<int>("SourceOrderMemberInviteId");

                    b.Property<int>("WithdrawDepositId");

                    b.HasKey("Id");

                    b.ToTable("IncomeAccounts");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.LxComputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("BorrowAmount");

                    b.Property<string>("BorrowCompany");

                    b.Property<string>("Cycle");

                    b.Property<string>("CycleAmount");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("MaxReduce");

                    b.Property<string>("MinReduce");

                    b.Property<string>("Name");

                    b.Property<string>("OverdueCycle");

                    b.Property<string>("Phone");

                    b.Property<string>("RepaymentCycle");

                    b.Property<string>("lastRefundDate");

                    b.Property<string>("sourcePhone");

                    b.HasKey("Id");

                    b.ToTable("LxComputers");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MailSrc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Body");

                    b.Property<string>("BodyText");

                    b.Property<string>("From");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrased");

                    b.Property<int>("MemberId");

                    b.Property<DateTime>("SendTime");

                    b.Property<string>("Sublic");

                    b.Property<string>("To");

                    b.Property<string>("Uid");

                    b.HasKey("Id");

                    b.ToTable("MailSrcs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Mailconfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Cookies");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<string>("Sid");

                    b.HasKey("Id");

                    b.ToTable("Mailconfigs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("AliPayAccount");

                    b.Property<string>("AliPayAccountName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("BusinessCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CityCode");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<string>("IdentityCardImgFront")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IdentityCardImgReverse")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IdentityCardNum")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("InviteId");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastLoginDate");

                    b.Property<int>("MemberIdentityState");

                    b.Property<int>("MemberVipType");

                    b.Property<decimal>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Nick");

                    b.Property<string>("Occupation");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordSalt");

                    b.Property<string>("Phone");

                    b.Property<string>("Photo");

                    b.Property<string>("QQ");

                    b.Property<int?>("QueryTimes");

                    b.Property<string>("RealName");

                    b.Property<int>("RegionId");

                    b.Property<string>("Remark");

                    b.Property<int>("RoleId");

                    b.Property<string>("RoleName");

                    b.Property<int>("Sex");

                    b.Property<int>("TopRegionId");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2021, 1, 19, 21, 51, 50, 298, DateTimeKind.Local).AddTicks(3840));

                    b.Property<string>("UserName");

                    b.Property<string>("WxOpenId");

                    b.Property<string>("WxUnionId");

                    b.Property<string>("WxUnionOpenId");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MemberBalanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal>("CurMoney")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Memberid");

                    b.Property<decimal>("OriginalMoney")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SourceId");

                    b.Property<int>("memberMoneySource");

                    b.HasKey("Id");

                    b.ToTable("MemberBalanceLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MemberIntegral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableIntegrals");

                    b.Property<int>("HistoryIntegrals");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberIntegrals");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MemberIntegralRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("Integral");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<string>("Remark");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberIntegralRecords");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<string>("MemberPhone");

                    b.Property<int>("OrderPaymentType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("OrderState");

                    b.Property<string>("ProducName");

                    b.Property<decimal>("ProductAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("ProductCount");

                    b.Property<int>("ProductId");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanUseMemberIntegral")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("Check");

                    b.Property<string>("Content");

                    b.Property<string>("Images");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("SalesVolume");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.Receivable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.ToTable("Receivables");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.ShareProfitConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId");

                    b.Property<int>("ShareProfitTemplateId");

                    b.HasKey("Id");

                    b.ToTable("ShareProfitConfigs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.SmsCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CheckState");

                    b.Property<int>("LastSendCode");

                    b.Property<DateTime>("LastSendTime");

                    b.Property<string>("Phone");

                    b.Property<int>("SendCnt");

                    b.HasKey("Id");

                    b.ToTable("SmsCheck");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.SysLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<string>("AdminName");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Log");

                    b.Property<int>("logType");

                    b.HasKey("Id");

                    b.ToTable("SysLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.SysParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SysParams");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.UpdateVipAuthCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Code");

                    b.Property<DateTime>("ExpiesTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberVipType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("OwinId");

                    b.Property<string>("Remark");

                    b.Property<int>("SourceId");

                    b.Property<int>("SourceOwinId");

                    b.Property<int>("UPdateVipAuthCodeState");

                    b.Property<int>("UsedMemberId");

                    b.Property<DateTime>("UsedTime");

                    b.HasKey("Id");

                    b.ToTable("UpdateVipAuthCodes");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.VoiceNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Duration");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("NeedVip");

                    b.Property<string>("Source");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("VoiceNews");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.WechatOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Out_Order_No")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PayDescription")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayState")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SubCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubState")
                        .HasColumnType("int");

                    b.Property<DateTime>("TranTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionID")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WechatOrders");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.WechatSubDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Last_Out_Order_No")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PayDescription")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Return_OrderID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubAccount")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SubAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubState")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SubTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SubType")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TransactionID")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WechatSubDetail");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.WechatSubLedgerReceivers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Describe")
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubType")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WechatSubLedgerReceivers");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.WithdrawDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId");

                    b.Property<decimal>("RealityAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Timestamp");

                    b.Property<decimal>("WithdrawCharge")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("WithdrawDepositState");

                    b.HasKey("Id");

                    b.ToTable("WithdrawDeposits");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.WithdrawDepositLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddUserId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WithdrawDepositId");

                    b.Property<int>("WithdrawDepositState");

                    b.HasKey("Id");

                    b.ToTable("WithdrawDepositLogs");
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.CouponReceive", b =>
                {
                    b.HasOne("Xw.Zx.Core.Models.Model.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("Couponid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MemberIntegral", b =>
                {
                    b.HasOne("Xw.Zx.Core.Models.Model.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Xw.Zx.Core.Models.Model.MemberIntegralRecord", b =>
                {
                    b.HasOne("Xw.Zx.Core.Models.Model.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
