# REST Client
@baseUrl = http://localhost:63836
#@baseUrl = http://localhost:52878
#@baseUrl = http://192.168.0.214:5000
#@baseUrl = http://122.114.157.240:8822
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE2MDc0NzY0MDIsImV4cCI6MTYxNjExNjQwMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MzgzNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYzODM2L3Jlc291cmNlcyIsIkFwcEFwaSJdLCJjbGllbnRfaWQiOiJBcHAuTWFuYWdlci5SbyIsInN1YiI6IjcyIiwiYXV0aF90aW1lIjoxNjA3NDc2NDAyLCJpZHAiOiIiLCJyb2xlIjoiQWRtaW4iLCJzY29wZSI6WyJBcHBBcGkiXSwiYW1yIjpbImN1c3RvbSJdfQ.oKBL9QZZTSqd9U2KVedcPMH9be8pwmxn91tEbW5VEDqoxJxuv_0lkvqulxwUoeA760kQO28OvZyyK7Lz6spoGjFH3NWt0SCGol3M6pjW5EpnXoGPqF8RErOrGygZm9OIkTu8-OwdcPTfK66CSSGmQ34EkM_BTuOWMQTSUlLmOdENOlqbsK2uPWx1DkikYlFwSisY4_vhLxMWkdG-G6miOaCvVHzp8lKRMxJL2uipa9a90ruByiNrAIZRaZsvzClUgt3thaDGw96D-UOFrGSlStnvoV1cbvMbIEh4f_ViTqRdP1M91_hMLvSpuZxdEizfFaabG6k3ZVTY644X-fP8kA
@contentType = application/json

# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=18624938007&password=123456

###############################################AutoSendMessages###############################################
### 获取已审核信息
GET {{baseUrl}}/api/Values/Get
#Authorization: Bearer {{token}}
###


### 
GET {{baseUrl}}/api/Member/GetMember?memberid=72
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/Member/Identity