# REST Client
@baseUrl = http://localhost:63836
#@baseUrl = http://localhost:52878
#@baseUrl = http://192.168.0.214:5000
#@baseUrl = http://122.114.157.240:8822
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImJiYTlkZGEyNGJmY2QxNDE1ODYxMGIyMTE4YWJlMTQ5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NjcyNDM2NDQsImV4cCI6MTU2NzI3MjQ0NCwiaXNzIjoiaHR0cDovLzEyMi4xMTQuMTU3LjI0MDo4ODIyIiwiYXVkIjpbImh0dHA6Ly8xMjIuMTE0LjE1Ny4yNDA6ODgyMi9yZXNvdXJjZXMiLCJBcHBBcGkiXSwiY2xpZW50X2lkIjoiQXBwLk1hbmFnZXIuUm8iLCJzdWIiOiIxMDIiLCJhdXRoX3RpbWUiOjE1NjcyNDM2NDQsImlkcCI6IiIsInJvbGUiOiIzIiwic2NvcGUiOlsiQXBwQXBpIl0sImFtciI6WyJjdXN0b20iXX0.FwkxofDSb98DEIbelCEHOafzTOT9cA2phJ3NttnfOJYkbklTWXKuRcYL_dugUS7FXHgicQArZkxsy9DWTa61ko4MA8zvGytppV6UZ6iFb5ec0nbypzdMOWgRwITs_judJZ7N-8mGWQH2brsM5r27YvVRJacBWi1KSuShluvtwFiY0_CpxP-8JuvBWnpMfiWeF6VfG2tTWLnGhuN6T1U8rJ7uxWO617FpSMD6ZzH8t3MNo5CRFZGqe22b1fefTAEiPNq2ohwGQUHsa32U1msJ5MLXGHIuCHWOC7qz050TlxJf7lcmgM9F8mfX1sMELB7f9sZHSPSWHYQxCj3DfoMD5w
@contentType = application/json

# 获取公用token 
POST {{baseUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=App.Manager.Ro&client_secret=DEsjpJFtokIOhMKuE6BVMczYUEEyPGTOLrur3PXw26VMLNwKOfAKFZZgR2vVJDKG&username=wengkui&password=wengkui3456

###############################################AutoSendMessages###############################################
### 获取已审核信息
GET {{baseUrl}}/api/Values/Get
#Authorization: Bearer {{token}}
###