<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <UserSecretsId>328cff38-aaa3-4a17-ab3b-2c2df5f1d84d</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <DocumentationFile>Xw.Zx.Core.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Manager\**" />
    <Content Remove="Areas\Manager\**" />
    <EmbeddedResource Remove="Areas\Manager\**" />
    <None Remove="Areas\Manager\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Api.http" />
    <None Remove="Xw.Zx.Core.xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Areas\Manager\ApplyForZx\ApplyForZxController.cs" />
    <Compile Include="Areas\Manager\ApplyForZx\ApplyForZxMDto.cs" />
    <Compile Include="Areas\Manager\Base\Dtos\SelectOptionDto.cs" />
    <Compile Include="Areas\Manager\Base\HbzsManagerResult.cs" />
    <Compile Include="Areas\Manager\Base\ManagerBaseController.cs" />
    <Compile Include="Areas\Manager\Income\IncomeAccountController.cs" />
    <Compile Include="Areas\Manager\Income\IncomeAccountMDto.cs" />
    <Compile Include="Areas\Manager\LxComputerController\Dtos\LxComputerMDto.cs" />
    <Compile Include="Areas\Manager\LxComputerController\LxComputerController.cs" />
    <Compile Include="Areas\Manager\Member\Dtos\ManagerMemberDto.cs" />
    <Compile Include="Areas\Manager\Member\Dtos\MemberMDto.cs" />
    <Compile Include="Areas\Manager\Member\Dtos\PostMemberMDto.cs" />
    <Compile Include="Areas\Manager\Member\MemberController.cs" />
    <Compile Include="Areas\Manager\Order\Dtos\OrderMDto.cs" />
    <Compile Include="Areas\Manager\Order\Dtos\OrderTotalMDto.cs" />
    <Compile Include="Areas\Manager\Order\OrderController.cs" />
    <Compile Include="Areas\Manager\Receivables\Dtos\ReceivablesMDto.cs" />
    <Compile Include="Areas\Manager\UpdateVipAuthCode\Dtos\PostUpdateVipAuthCodeMDto.cs" />
    <Compile Include="Areas\Manager\UpdateVipAuthCode\Dtos\UpdateVipAuthCodeMDto.cs" />
    <Compile Include="Areas\Manager\UpdateVipAuthCode\UpdateVipAuthCodeController.cs" />
    <Compile Include="Areas\Manager\UpdateVip\PostUpdateVipMDto.cs" />
    <Compile Include="Areas\Manager\UpdateVip\UpdateVipController.cs" />
    <Compile Include="Areas\Manager\WithdrawDeposit\Dtos\AuditWithdrawDepositdetailDto.cs" />
    <Compile Include="Areas\Manager\WithdrawDeposit\Dtos\GetAuditWithdrawDepositdetailDto.cs" />
    <Compile Include="Areas\Manager\WithdrawDeposit\Dtos\WithdrawDepositMDto.cs" />
    <Compile Include="Areas\Manager\WithdrawDeposit\Dtos\WithdrawDepositTotalMDto.cs" />
    <Compile Include="Areas\Manager\WithdrawDeposit\WithdrawDepositController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Api.http">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Xw.Zx.Core.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alipay.AopSdk.AspnetCore" Version="2.4.3" />
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.12" />
    <PackageReference Include="IdentityServer4" Version="2.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="3.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.8.4" />
    <PackageReference Include="qcloud.qcloudsms_csharp" Version="0.1.6" />
    <PackageReference Include="S22.Imap.Core" Version="3.6.1" />
    <PackageReference Include="Sieve" Version="2.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
    <Folder Include="UpLoad\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
